### ISSUE TITLE
clicking on "Ask HN" enteries gives 404

### ISSUE THREAD

**Issue by Yiabiten** [melbarch/next-hn#1]
![image](https://user-images.githubusercontent.com/5012992/82741536-a7fd0200-9d42-11ea-820b-3f9e728b5aa4.png)
![image](https://user-images.githubusercontent.com/5012992/82741548-c5ca6700-9d42-11ea-9fe4-ec9aa93e3dbb.png)

**Comment by melbarch** [comment]
Nice catch! sounds like a relative url is returned for 'Ask items'

**Comment by melbarch** [comment]
and if you are still interested in who regrets choosing Elixir here are the answer 😆 🤣
